AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectName:
    Description: "Project name"
    Type: "String"
  Environment:
    Description: "Server environment"
    Type: "String"
    AllowedValues:
      - "test"
      - "prod"
  VpcId:
    Description: "VPC Id"
    Type: "String"
  SubnetIds:
    Type: "List<AWS::EC2::Subnet::Id>"
  InstanceType:
    Type: "String"
    Default: "t3.micro"
  ServiceRoleARN:
    Type: "String"
  NotificationsEmail:
    Type: "String"
  LoadBalancerARN:
    Type: "String"
  EbApplicationName:
    Type: "String"
  ElbSecurityGroupId:
    Type: "String"
  PlatformARN:
    Type: "String"
  KmsKeyAlias:
    Type: "String"
  InstanceRoleName:
    Type: "String"

Resources:
  EbSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: !Sub "${ProjectName}-${Environment}-eb-sg"
      GroupDescription: !Sub "${ProjectName}-${Environment}-eb-sg"
      VpcId: !Ref "VpcId"
      SecurityGroupIngress:
        - Description: "Load balancer"
          IpProtocol: "tcp"
          FromPort: 8081
          ToPort: 8081
          SourceSecurityGroupId: !Ref "ElbSecurityGroupId"
      Tags:
        - Key: "Name"
          Value: !Sub "${ProjectName}-${Environment}-eb-sg"
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"

  ElasticConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref "EbApplicationName"
      PlatformArn: !Ref "PlatformARN"
      OptionSettings:
        # Temporary hack to force the usage of LaunchTemplates,
        # instead of the obsolete LaunchConfigurations, while AWS
        # makes this the default. See
        # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/environments-cfg-autoscaling-launch-templates.html
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: RootVolumeType
          Value: "gp3"
        # Capacity
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: "LoadBalanced"
        - Namespace: aws:autoscaling:asg
          OptionName: MinSize
          Value: "1"
        - Namespace: aws:autoscaling:asg
          OptionName: MaxSize
          Value: "1"
        # Instance type
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: InstanceType
          Value: !Ref "InstanceType"
        # Network
        - Namespace: aws:ec2:vpc
          OptionName: VPCId
          Value: !Ref "VpcId"
        - Namespace: aws:ec2:vpc
          OptionName: AssociatePublicIpAddress
          Value: "true"
        - Namespace: aws:ec2:vpc
          OptionName: Subnets
          Value: !Join [",", !Ref "SubnetIds"]
        - Namespace: aws:ec2:vpc
          OptionName: ELBSubnets
          Value: !Join [",", !Ref "SubnetIds"]
        # Security
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: ServiceRole
          Value: !Ref "ServiceRoleARN"
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref "InstanceProfile"
          # Avoid the creation of the default security group that
          # opens the SSH port to the outside world, and use only our
          # own. See https://github.com/aws/elastic-beanstalk-roadmap/issues/44
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: SecurityGroups
          Value: !Ref "EbSecurityGroup"
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: DisableDefaultEC2SecurityGroup
          Value: "true"
        # Notifications
        - Namespace: aws:elasticbeanstalk:sns:topics
          OptionName: Notification Endpoint
          Value: !Ref "NotificationsEmail"
        # Load balancer
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerIsShared
          Value: "true"
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: LoadBalancerType
          Value: "application"
        - Namespace: aws:elbv2:loadbalancer
          OptionName: SharedLoadBalancer
          Value: !Ref "LoadBalancerARN"
        - Namespace: aws:elbv2:loadbalancer
          OptionName: SecurityGroups
          Value: !Ref "ElbSecurityGroupId"
        - Namespace: aws:elbv2:listener:443
          OptionName: Rules
          Value: "default"
        - Namespace: aws:elasticbeanstalk:environment:process:default
          OptionName: Port
          Value: "8081"
        # Software
        - Namespace: aws:elasticbeanstalk:managedactions
          OptionName: ManagedActionsEnabled
          Value: "true"
        - Namespace: aws:elasticbeanstalk:managedactions
          OptionName: PreferredStartTime
          Value: "Sat:03:00"
        - Namespace: aws:elasticbeanstalk:managedactions:platformupdate
          OptionName: UpdateLevel
          Value: "minor"
        - Namespace: aws:elasticbeanstalk:hostmanager
          OptionName: LogPublicationControl
          Value: "true"
        # Environment variables
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: PROJECT_NAME
          Value: !Ref "ProjectName"
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: ENVIRONMENT
          Value: !Ref "Environment"
        - Namespace: aws:elasticbeanstalk:application:environment
          OptionName: KMS_KEY_ALIAS
          Value: !Ref "KmsKeyAlias"

  ElasticEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref "EbApplicationName"
      TemplateName: !Ref "ElasticConfigurationTemplate"
      EnvironmentName: !Sub "${ProjectName}-${Environment}"
      Tags:
        - Key: "project-name"
          Value: !Ref "ProjectName"
        - Key: "environment"
          Value: !Ref "Environment"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref "InstanceRoleName"

Outputs:
  EbEnvironmentName:
    Description: "EB environment Name"
    Value: !Ref "ElasticEnvironment"
  EbEnvironmentURL:
    Description: "EB endpoint URL"
    Value: !GetAtt "ElasticEnvironment.EndpointURL"
  EbSecurityGroupId:
    Description: "EB security group ID"
    Value: !Ref "EbSecurityGroup"
